apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ugctestgrid
  region: eu-west-1

iam:
  withOIDC: true
 # serviceAccounts:
 # - metadata:
 #     name: ugcupload-jmeter
 #     # if no namespace is set, "default" will be used;
 #     # the namespace will be created if it doesn't exist already
 #     namespace: ugctestgrid-jmeter-ns
 #     labels: {aws-usage: "application"}
 #   attachPolicyARNs:
 #   - "arn:aws:iam::546933502184:policy/ugcupload-eks-jmeter-policy"

nodeGroups:
  - name: jmeter-slaves-v2
    labels: { jmeter_mode : slaves }
    taints:
      jmeter_slave: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jmeter_mode: slaves
      k8s.io/cluster-autoscaler/node-template/taint/jmeter_slave: "true:NoSchedule"
    minSize: 2
    maxSize: 100
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro

  - name: jmeter-slaves-t2-medium-v2
    labels: { jmeter_mode : slaves }
    taints:
      jmeter_slave: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jmeter_mode: slaves
      k8s.io/cluster-autoscaler/node-template/taint/jmeter_slave: "true:NoSchedule"
    minSize: 2
    maxSize: 100
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.medium
  
  - name: jmeter-slaves-t2-xlarge-v2
    labels: { jmeter_mode : slaves }
    taints:
      jmeter_slave: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jmeter_mode: slaves
      k8s.io/cluster-autoscaler/node-template/taint/jmeter_slave: "true:NoSchedule"
    minSize: 2
    maxSize: 100
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.xlarge

  - name: jmeter-master-v2
    labels: { jmeter_mode : master }
    taints:
      jmeter_master: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/jmeter_mode: master
      k8s.io/cluster-autoscaler/node-template/taint/jmeter_master: "true:NoSchedule"
    minSize: 1
    maxSize: 25
    volumeSize: 50
    volumeType: gp2
    instanceType: t2.small
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true

  - name: grafana-v5
    labels: { report : grafana }
    taints:
      grafana: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/report: grafana
      k8s.io/cluster-autoscaler/node-template/taint/grafana: "true:NoSchedule"
    minSize: 3
    maxSize: 3
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro
    availabilityZones: ["eu-west-1a"]

  - name: influxdb-v2
    labels: { report : influxdb }
    taints:
      influxdb: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/report: influxdb
      k8s.io/cluster-autoscaler/node-template/taint/influxdb: "true:NoSchedule"
    minSize: 3
    maxSize: 3
    volumeSize: 50
    volumeType: gp2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.micro
    availabilityZones: ["eu-west-1a"]

  - name: admin-controller-v4
    labels: { control : admin }
    taints:
      admin: "true:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/control: admin
      k8s.io/cluster-autoscaler/node-template/taint/admin: "true:NoSchedule"
    minSize: 4
    maxSize: 4
    volumeSize: 50
    volumeType: gp2
    ssh:
      allow: true
      publicKeyName: 'loadtest-controller'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.medium

  - name: management
    labels: { management : admin }
    minSize: 4
    maxSize: 4
    volumeSize: 50
    volumeType: gp2
    ssh:
      allow: true
      publicKeyName: 'loadtest-controller'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        ebs: true
    instanceType: t2.medium
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["all"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"

