apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "influxdb-pv" 
spec:
  storageClassName: influx-db-sc
  capacity:
    storage: "40Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain   
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-079951934bf22c463"

